#!/bin/bash

COMMAND=$1
FILE=$2

if [ "$COMMAND" == "run" ]; then
    if [ -z "$FILE" ]; then
        echo "Usage: fax run <file.fax>"
        exit 1
    fi
    # Build and get the binary name
    OUTPUT=$(npm start --quiet -- "$FILE")
    EXIT_CODE=$?
    
    if [ $EXIT_CODE -eq 0 ]; then
        BIN_NAME=$(basename "$FILE" .fax)
        if [ -f "./$BIN_NAME" ]; then
            echo -e "
--- Running Binary: $BIN_NAME ---
"
            ./$BIN_NAME
            echo -e "
--- Finished ---
"
            # Optional: hapus binary setelah dijalankan jika ingin benar-benar bersih
            # rm "./$BIN_NAME"
        fi
    else
        echo "Compilation failed."
        exit 1
    fi

elif [ "$COMMAND" == "build" ]; then
    npm start -- "$FILE"
else
    echo "Fax Compiler Tool"
    echo "Usage:"
    echo "  fax run <file.fax>   - Compile and execute immediately"
    echo "  fax build <file.fax> - Compile to native binary"
fi
