import sys, subprocess, shutil
from pathlib import Path
from typing import Optional
from .ui import UI
from .config import FaxConfig

class Toolchain:
    def __init__(self):
        self.install_root = Path(__file__).resolve().parent.parent.parent / "faxc"
        self.root = self._find_root(Path.cwd())
        self.config = FaxConfig(self.root) if self.root else None

    def _find_root(self, start: Path) -> Optional[Path]:
        for p in [start, *start.parents]:
            if (p / "Fax.toml").exists(): return p
        return None

    def run_pipeline(self, file_path: str, release: bool = False) -> Optional[Path]:
        p = Path(file_path)
        if not p.exists():
            UI.error(f"File not found: {file_path}")
            return None
            
        abs_file_path = p.resolve()
        bin_name = abs_file_path.stem
        hub_dir = self.install_root / "packages" / "hub"
        
        cmd = ["npm", "start", "--", str(abs_file_path)]
        if release: cmd.append("--release")
        
        try:
            process = subprocess.run(cmd, cwd=str(hub_dir), capture_output=True, text=True)
            if process.returncode != 0:
                print(f"{UI.RED}{UI.BOLD}Compilation Failed{UI.RESET}\n")
                if process.stdout: print(f"{UI.GRAY}STDOUT:{UI.RESET}\n{process.stdout}")
                if process.stderr: print(f"{UI.RED}STDERR:{UI.RESET}\n{process.stderr}")
                return None
            
            llvm_ir = process.stdout.strip()
            if "; Generated by Fax" in llvm_ir:
                llvm_ir = llvm_ir[llvm_ir.find("; Generated by Fax"):]
            
            if not llvm_ir.startswith(";") and not "define" in llvm_ir:
                if "check" in sys.argv: return Path("/dev/null")
                UI.error("Compiler finished but no LLVM IR was produced.")
                return None
                
        except Exception as e:
            UI.error(f"Execution error: {e}")
            return None

        base_dir = self.root if self.root else Path.cwd()
        target_dir = base_dir / "target"
        target_dir.mkdir(parents=True, exist_ok=True)
        
        llvm_file = target_dir / f"{bin_name}.ll"
        final_bin_path = target_dir / bin_name
        
        with open(llvm_file, "w") as f: f.write(llvm_ir)
            
        if "check" in sys.argv: return Path("/dev/null")

        UI.status("Linking", f"{bin_name}")
        lib_rt = self.install_root / "packages" / "runtime" / "zig-out" / "lib" / "libfaxruntime.a"
        
        link_cmd = [
            "zig", "cc", str(llvm_file), str(lib_rt),
            "-o", str(final_bin_path),
            "-Wno-override-module", "-lc", "-O2", "-g"
        ]
        
        try:
            link_proc = subprocess.run(link_cmd, capture_output=True, text=True)
            if link_proc.returncode != 0:
                UI.error(f"Linking failed: {link_proc.stderr}")
                return None
            final_bin_path.chmod(0o755)
            return final_bin_path
        except Exception as e:
            UI.error(f"Linking error: {e}")
            return None