# Stale bot configuration to automatically close inactive issues
# https://github.com/actions/stale

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60

# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7

# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - good first issue
  - help wanted
  - bug
  - critical

# Label to use when marking an issue as stale
staleLabel: stale

# Comment to post when marking an issue as stale
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
  
  If you believe this is still an issue, please comment with an update.

# Comment to post when closing a stale issue
closeComment: >
  This issue has been automatically closed due to inactivity. Please feel free
  to reopen it if you believe it's still relevant, or create a new issue with
  updated information.

# Limit the number of actions per hour
limitPerRun: 30

# Only process issues (not PRs)
only: issues

# Operations to perform
operationsPerRun: 10
