#include "codegen.hpp"
#include "instruction_builder.hpp"
#include <algorithm>
#include <sstream>

namespace fax {
namespace codegen {

Codegen::Codegen(const json& data) : ast(data) {}

bool Codegen::isPointerType(const std::string& type) {
    return structMeta.count(type) || type.find("[]") != std::string::npos ||
           type == "str" || type == "string" || type == "array" || type == "struct";
}

bool Codegen::isStringType(const std::string& type) {
    return type == "str" || type == "string";
}

std::string Codegen::ensurePointer(Info info, int level) {
    std::string val = toRegister(info, level);
    int id = lbl++;
    indent(level); std::cout << "%ptr" << id << " = inttoptr i64 " << val << " to i8*\n";
    return "%ptr" + std::to_string(id);
}

std::string Codegen::mangle(const std::string& name) {
    if (scopes.count(name) && !scopes[name].empty()) {
        return name + "_" + std::to_string(scopes[name].back());
    }
    return name + "_0";
}

std::string Codegen::resolve(const std::string& name) {
    if (scopes.count(name) && !scopes[name].empty()) {
        return "%" + name + "_" + std::to_string(scopes[name].back()) + "_ptr";
    }
    return globals.count(name) ? "@" + name : "%" + name + "_ptr";
}

void Codegen::indent(int level) {
    for (int i = 0; i < level; ++i) std::cout << "    ";
}

void Codegen::emitHeader() {
    std::cout << "; Generated by Fax Codegen\n";
    std::cout << "declare void @fax_fgc_init()\n";
    std::cout << "declare i8* @fax_fgc_alloc(i64, i64*, i64)\n";
    std::cout << "declare i8* @fax_fgc_alloc_array(i64, i64, i1)\n";
    std::cout << "declare void @fax_fgc_collect()\n";
    std::cout << "declare void @fax_fgc_push_frame(i8*)\n";
    std::cout << "declare void @fax_fgc_pop_frame()\n";
    std::cout << "declare i8* @fax_str_concat(i8*, i8*)\n";
    std::cout << "declare i64 @printf(i8*, ...)\n\n";
    std::cout << "@f_int = private constant [5 x i8] c\"%ld\\0A\\00\"\n";
    std::cout << "@f_str = private constant [4 x i8] c\"%s\\0A\\00\"\n";
    std::cout << "@f_t = private constant [6 x i8] c\"true\\0A\\00\"\n";
    std::cout << "@f_f = private constant [7 x i8] c\"false\\0A\\00\"\n\n";
}

void Codegen::defineGlobal(const json& node) {
    if (!node.contains("name")) return;
    std::string name = node["name"];
    globals.insert(name);

    long initialValue = 0;
    if (node.contains("expr")) {
        auto& expr = node["expr"];
        if (expr.is_number()) initialValue = expr.get<long>();
        else if (expr.is_string()) {
            try { initialValue = std::stol(expr.get<std::string>()); } catch(...) {}
        }
        else if (expr.is_object() && expr.contains("value")) {
            try { initialValue = std::stol(expr["value"].get<std::string>()); } catch(...) {}
        }
    }
    std::cout << "@" << name << " = global i64 " << initialValue << "\n";
}

void Codegen::process(const json& nodes) {
    if (!nodes.is_array()) return;

    for (auto& node : nodes) {
        if (!node.is_object() || !node.contains("type")) continue;
        std::string type = node["type"];

        if (type == "StructDeclaration") {
            if (!node.contains("name")) continue;
            std::string name = node["name"];
            structMeta[name] = {};
            std::vector<int> pmap;
            std::cout << "%struct." << name << " = type { ";
            if (node.contains("fields")) {
                for (int i = 0; i < (int)node["fields"].size(); ++i) {
                    auto& field = node["fields"][i];
                    if (field.contains("name")) {
                        std::string fieldName = field["name"];
                        structMeta[name][fieldName] = i;
                        std::string ft = field.contains("type") ? field["type"].get<std::string>() : "i64";
                        fieldTypes[name][fieldName] = ft;
                        if (isPointerType(ft)) {
                            pmap.push_back(i * 8);
                        }
                    }
                    std::cout << (i > 0 ? ", i64" : "i64");
                }
            }
            std::cout << " }\n";
            if (!pmap.empty()) {
                std::cout << "@pmap." << name << " = private constant [" << pmap.size() << " x i64] [";
                for (size_t i = 0; i < pmap.size(); ++i) {
                    std::cout << (i > 0 ? ", " : "") << "i64 " << pmap[i];
                }
                std::cout << "]\n";
            }
        } else if (type == "VariableDeclaration") {
            defineGlobal(node);
        }
    }

    for (auto& node : nodes) {
        if (node.is_object() && node.value("type", "") == "FunctionDeclaration" && node.contains("name")) {
            returns[node["name"]] = node.value("returnType", "void");
        }
    }

    for (auto& node : nodes) {
        if (node.is_object() && node.value("type", "") == "FunctionDeclaration") {
            emitFunction(node);
        }
    }
}

void Codegen::emitStatement(const json& node, int level) {
    if (!node.is_object() || !node.contains("type")) return;
    std::string type = node["type"];

    if (type == "VariableDeclaration") defineVariable(node, level);
    else if (type == "IfStatement") emitIf(node, level);
    else if (type == "WhileStatement") emitWhile(node, level);
    else if (type == "ForStatement") emitFor(node, level);
    else if (type == "Assignment") emitAssignment(node, level);
    else if (type == "CallExpression") {
        std::string name = node.value("name", "");
        if (name == "print") emitPrint(node, level);
        else if (name == "collect_gc") {
            indent(level); std::cout << "call void @fax_fgc_collect()\n";
        }
        else emitCall(node, level);
    }
    else if (type == "ReturnStatement") emitReturn(node, level);
    else if (type == "BreakStatement") {
        if (!loops.empty()) { indent(level); std::cout << "br label %f" << loops.back().end << "\n"; }
    }
    else if (type == "ContinueStatement") {
        if (!loops.empty()) { indent(level); std::cout << "br label %c" << loops.back().start << "\n"; }
    }
    else if (type == "Block") emitBlock(node, level);
}

void Codegen::emitBlock(const json& node, int level) {
    std::map<std::string, size_t> checkpoint;
    for (auto const& [name, ids] : scopes) checkpoint[name] = ids.size();

    const json* body = (node.is_object() && node.contains("body")) ? &node["body"] : &node;
    if (body->is_array()) {
        for (auto& stmt : *body) emitStatement(stmt, level);
    }

    for (auto const& [name, size] : checkpoint) {
        while (scopes[name].size() > size) scopes[name].pop_back();
    }
}

Info Codegen::load(const json& node, int level) {
    if (node.is_string()) {
        std::string val = node.get<std::string>();
        if (!val.empty() && isdigit(val[0])) return {val, "i64"};
        if (symbols.count(val) && symbols[val] == "arg") {
            int id = lbl++;
            indent(level);
            std::cout << "%a" << id << " = add i64 %arg_" << val << ", 0\n";
            return {"%a" + std::to_string(id), "i64"};
        }
        std::string ptr = resolve(val);
        std::string mangled = mangle(val);
        int id = lbl++;
        std::string type = types.count(mangled) ? types[mangled] : "i64";
        if (pointers.count(mangled)) {
            indent(level);
            std::cout << "%r" << id << " = load i8*, i8** " << ptr << "\n";
            return {"%r" + std::to_string(id), pointers[mangled] == "struct" ? types[mangled] : pointers[mangled]};
        }
        indent(level);
        std::cout << "%t" << id << " = load i64, i64* " << ptr << "\n";
        return {"%t" + std::to_string(id), type};
    }

    if (!node.is_object() || !node.contains("type")) return {"0", "i64"};
    std::string type = node["type"];

    if (type == "NumberLiteral") return {node.value("value", "0"), "i64"};
    if (type == "Identifier") {
        std::string val = node.value("value", "");
        if (symbols.count(val) && symbols[val] == "arg") {
            int id = lbl++;
            indent(level);
            std::cout << "%a" << id << " = add i64 %arg_" << val << ", 0\n";
            return {"%a" + std::to_string(id), "i64"};
        }
        std::string ptr = resolve(val);
        std::string mangled = mangle(val);
        int id = lbl++;
        std::string varType = types.count(mangled) ? types[mangled] : "i64";
        if (pointers.count(mangled)) {
            indent(level);
            std::cout << "%r" << id << " = load i8*, i8** " << ptr << "\n";
            return {"%r" + std::to_string(id), varType};
        }
        indent(level);
        std::cout << "%t" << id << " = load i64, i64* " << ptr << "\n";
        return {"%t" + std::to_string(id), varType};
    }

    if (type == "Boolean") return {node.value("value", "false") == "true" ? "1" : "0", "bool"};

    if (type == "NullLiteral") return {"0", "null"};

    if (type == "StringLiteral") {
        std::string val = node.value("value", "");
        if (!strings.count(val)) strings[val] = "s" + std::to_string(str++);
        int id = lbl++;
        indent(level);
        std::cout << "%p" << id << " = getelementptr [" << (int)val.length()+1 << " x i8], [" << (int)val.length()+1 << " x i8]* @" << strings[val] << ", i32 0, i32 0\n";
        return {"%p" + std::to_string(id), "string"};
    }

    if ((type == "BinaryExpression" || type == "ComparisonExpression") && node.contains("left") && node.contains("right")) {
        Info leftInfo = load(node["left"], level);
        Info rightInfo = load(node["right"], level);
        std::string op = node.value("op", "add");
        std::string id = std::to_string(lbl++);

        if (op == "add" && isStringType(leftInfo.type) && isStringType(rightInfo.type)) {
            indent(level);
            std::cout << "%sc" << id << " = call i8* @fax_str_concat(i8* " << leftInfo.reg << ", i8* " << rightInfo.reg << ")\n";
            return {"%sc" + id, "string"};
        }

        std::string leftVal = toRegister(leftInfo, level);
        std::string rightVal = toRegister(rightInfo, level);

        if (type == "ComparisonExpression") {
            std::string cmp = (op == "eq") ? "eq" : (op == "ne") ? "ne" : (op == "slt") ? "slt" : (op == "sgt") ? "sgt" : (op == "sle") ? "sle" : "sge";
            indent(level);
            std::cout << "%cmp" << id << " = icmp " << cmp << " i64 " << leftVal << ", " << rightVal << "\n";
            indent(level);
            std::cout << "%z" << id << " = zext i1 %cmp" << id << " to i64\n";
            return {"%z" + id, "bool"};
        }

        indent(level);
        std::cout << "%b" << id << " = " << op << " i64 " << leftVal << ", " << rightVal << "\n";
        return {"%b" + id, "i64"};
    }

    if (type == "CallExpression") {
        std::vector<std::string> args;
        if (node.contains("args")) {
            for (auto& arg : node["args"]) args.push_back(toRegister(load(arg, level), level));
        }
        std::string name = node.value("name", "");
        std::string retType = returns.count(name) ? returns[name] : "i64";
        size_t p = 0;
        while ((p = name.find("::", p)) != std::string::npos) { name.replace(p, 2, "_"); p += 1; }
        int id = lbl++;
        indent(level);
        std::cout << "%ig" << id << " = call i64 @" << name << "(";
        for (size_t i = 0; i < args.size(); ++i) std::cout << (i > 0 ? ", " : "") << "i64 " << args[i];
        std::cout << ")\n";

        if (isPointerType(retType)) {
            int castId = lbl++;
            indent(level); std::cout << "%cp" << castId << " = inttoptr i64 %ig" << id << " to i8*\n";
            return {"%cp" + std::to_string(castId), retType};
        }
        return {"%ig" + std::to_string(id), retType};
    }

    if (type == "StructLiteral") {
        std::string name = node.value("name", "");
        int id = lbl++;
        int count = node["fields"].size();

        // Find pointer map for this struct
        std::string pmap_name = "null";
        int pmap_len = 0;

        // We need to re-scan to find pmap size, or store it in a map.
        // For simplicity, let's just re-calculate since we know the fields.
        // Actually, I already emitted @pmap.name in process().
        // Let's check how many fields are pointers.
        for (auto const& [f, t] : fieldTypes[name]) {
            if (isPointerType(t)) {
                pmap_len++;
            }
        }

        if (pmap_len > 0) {
            pmap_name = "getelementptr ([" + std::to_string(pmap_len) + " x i64], [" + std::to_string(pmap_len) + " x i64]* @pmap." + name + ", i32 0, i32 0)";
        }

        indent(level); std::cout << "%sr" << id << " = call i8* @fax_fgc_alloc(i64 " << (long)count * 8 << ", i64* " << pmap_name << ", i64 " << (long)pmap_len << ")\n";
        indent(level); std::cout << "%sc" << id << " = bitcast i8* %sr" << id << " to %struct." << name << "*\n";
        for (auto& field : node["fields"]) {
            std::string fieldName = field.value("name", "");
            int index = structMeta[name][fieldName];
            std::string val = toRegister(load(field["expr"], level), level);
            indent(level); std::cout << "%sf" << id << "_" << index << " = getelementptr %struct." << name << ", %struct." << name << "* %sc" << id << ", i32 0, i32 " << index << "\n";
            indent(level); std::cout << "store i64 " << val << ", i64* %sf" << id << "_" << index << "\n";
        }
        return {"%sr" + std::to_string(id), name};
    }

    if (type == "MemberAccess") {
        Info baseInfo = load(node["base"], level);
        std::string baseReg = ensurePointer(baseInfo, level);

        std::string field = node.value("field", "");
        std::string structType = baseInfo.type;
        int index = structMeta[structType][field];
        int id = lbl++;
        indent(level);
        std::cout << "%c" << id << " = bitcast i8* " << baseReg << " to %struct." << structType << "*\n";
        indent(level);
        std::cout << "%g" << id << " = getelementptr %struct." << structType << ", %struct." << structType << "* %c" << id << ", i32 0, i32 " << index << "\n";
        std::string fieldType = fieldTypes[structType][field];
        indent(level);
        std::cout << "%v" << id << " = load i64, i64* %g" << id << "\n";
        if (isPointerType(fieldType)) {
            int castId = lbl++;
            indent(level);
            std::cout << "%cp" << castId << " = inttoptr i64 %v" << id << " to i8*\n";
            return {"%cp" + std::to_string(castId), fieldType};
        }
        return {"%v" + std::to_string(id), fieldType};
    }

    if (type == "IndexAccess") {
        Info baseInfo = load(node["base"], level);
        std::string baseReg = ensurePointer(baseInfo, level);

        std::string indexVal = toRegister(load(node["index"], level), level);
        std::string elemType = "i64";
        if (baseInfo.type.length() > 2 && baseInfo.type.substr(baseInfo.type.length() - 2) == "[]") {
            elemType = baseInfo.type.substr(0, baseInfo.type.length() - 2);
        }

        int id = lbl++;
        indent(level);
        std::cout << "%ap" << id << " = bitcast i8* " << baseReg << " to i64*\n";
        indent(level);
        std::cout << "%ge" << id << " = getelementptr i64, i64* %ap" << id << ", i64 " << indexVal << "\n";
        indent(level);
        std::cout << "%vi" << id << " = load i64, i64* %ge" << id << "\n";

        if (isPointerType(elemType)) {
            int castId = lbl++;
            indent(level); std::cout << "%cp" << castId << " = inttoptr i64 %vi" << id << " to i8*\n";
            return {"%cp" + std::to_string(castId), elemType};
        }
        return {"%vi" + std::to_string(id), elemType};
    }

    if (type == "ArrayLiteral") {
        int count = 0;
        if (node.contains("elements")) count = node["elements"].size();

        bool isPtrArray = false;
        if (count > 0) {
            Info first = load(node["elements"][0], level);
            if (isPointerType(first.type)) isPtrArray = true;
        }

        int id = lbl++;
        indent(level);
        std::cout << "%ar" << id << " = call i8* @fax_fgc_alloc_array(i64 8, i64 " << (long)count << ", i1 " << (isPtrArray ? "1" : "0") << ")\n";
        indent(level);
        std::cout << "%ac" << id << " = bitcast i8* %ar" << id << " to i64*\n";
        for (int i = 0; i < count; ++i) {
            std::string val = toRegister(load(node["elements"][i], level), level);
            indent(level);
            std::cout << "%agep" << id << "_" << i << " = getelementptr i64, i64* %ac" << id << ", i64 " << i << "\n";
            indent(level);
            std::cout << "store i64 " << val << ", i64* %agep" << id << "_" << i << "\n";
        }
        return {"%ar" + std::to_string(id), "array"};
    }

    return {"0", "i64"};
}

std::string Codegen::toRegister(Info info, int level) {
    if (!info.reg.empty() && info.reg[0] == '%' && isPointerType(info.type)) {
        int id = lbl++;
        indent(level);
        std::cout << "%c64_" << id << " = ptrtoint i8* " << info.reg << " to i64\n";
        return "%c64_" + std::to_string(id);
    }
    return info.reg;
}

void Codegen::defineVariable(const json& node, int level) {
    if (!node.contains("name")) return;
    std::string name = node["name"];
    int id = nodeIds[&node];
    scopes[name].push_back(id);
    std::string mangled = name + "_" + std::to_string(id);
    std::string ptr = "%" + mangled + "_ptr";

    if (node.contains("expr")) {
        Info res = load(node["expr"], level);
        std::string val = toRegister(res, level);
        if (pointers.count(mangled)) {
            int castId = lbl++;
            indent(level);
            std::cout << "%pv" << castId << " = inttoptr i64 " << val << " to i8*\n";
            indent(level);
            std::cout << "store i8* %pv" << castId << ", i8** " << ptr << "\n";
        } else {
            indent(level);
            std::cout << "store i64 " << val << ", i64* " << ptr << "\n";
        }
    }
}

void Codegen::emitAssignment(const json& node, int level) {
    if (!node.contains("expr") || !node.contains("target")) return;
    std::string val = toRegister(load(node["expr"], level), level);
    const json& target = node["target"];

    if (target.is_object() && target.value("type", "") == "MemberAccess") {
        Info baseInfo = load(target["base"], level);
        std::string field = target.value("field", "");
        std::string structType = baseInfo.type;
        int index = structMeta[structType][field];
        int id = lbl++;
        indent(level); std::cout << "%ca" << id << " = bitcast i8* " << baseInfo.reg << " to %struct." << structType << "*\n";
        indent(level); std::cout << "%ga" << id << " = getelementptr %struct." << structType << ", %struct." << structType << "* %ca" << id << ", i32 0, i32 " << index << "\n";
        indent(level); std::cout << "store i64 " << val << ", i64* %ga" << id << "\n";
    } else if (target.is_object() && target.value("type", "") == "IndexAccess") {
        Info baseInfo = load(target["base"], level);
        std::string indexVal = toRegister(load(target["index"], level), level);
        int id = lbl++;
        indent(level); std::cout << "%ap" << id << " = bitcast i8* " << baseInfo.reg << " to i64*\n";
        indent(level); std::cout << "%ge" << id << " = getelementptr i64, i64* %ap" << id << ", i64 " << indexVal << "\n";
        indent(level); std::cout << "store i64 " << val << ", i64* %ge" << id << "\n";
    } else if (target.is_object() && target.value("type", "") == "Identifier") {
        std::string name = target["value"];
        std::string ptr = resolve(name);
        std::string mangled = mangle(name);
        if (pointers.count(mangled)) {
            int id = lbl++;
            indent(level);
            std::cout << "%cv" << id << " = inttoptr i64 " << val << " to i8*\n";
            indent(level);
            std::cout << "store i8* %cv" << id << ", i8** " << ptr << "\n";
        } else {
            indent(level);
            std::cout << "store i64 " << val << ", i64* " << ptr << "\n";
        }
    }
}

void Codegen::emitIf(const json& node, int level) {
    std::string cond = toRegister(load(node["condition"], level), level);
    int id = lbl++;
    indent(level); std::cout << "%cb" << id << " = icmp ne i64 " << cond << ", 0\n";
    bool hasElse = node.contains("else_branch") && !node["else_branch"].empty();
    indent(level); std::cout << "br i1 %cb" << id << ", label %t" << id << ", label %" << (hasElse ? "e" : "f") << id << "\n\nt" << id << ":\n";
    emitBlock(node["then_branch"], level + 1);
    indent(level + 1); std::cout << "br label %f" << id << "\n";
    if (hasElse) { std::cout << "e" << id << ":\n"; emitBlock(node["else_branch"], level + 1); indent(level + 1); std::cout << "br label %f" << id << "\n"; }
    std::cout << "f" << id << ":\n";
}

void Codegen::emitWhile(const json& node, int level) {
    int id = lbl++;
    indent(level); std::cout << "br label %c" << id << "\nc" << id << ":\n";
    std::string cond = toRegister(load(node["condition"], level + 1), level + 1);
    indent(level + 1); std::cout << "%cm" << id << " = icmp ne i64 " << cond << ", 0\n";
    indent(level + 1); std::cout << "br i1 %cm" << id << ", label %b" << id << ", label %f" << id << "\nb" << id << ":\n";
    loops.push_back({id, id});
    emitBlock(node["body"], level + 1);
    loops.pop_back();
    indent(level + 1); std::cout << "br label %c" << id << "\nf" << id << ":\n";
}

void Codegen::emitFor(const json& node, int level) {
    std::string var = node["var_name"];
    int id = lbl++, sid = lbl++;
    scopes[var].push_back(sid);
    std::string ptr = "%" + var + "_" + std::to_string(sid) + "_ptr";
    indent(level); std::cout << ptr << " = alloca i64\n";
    indent(level); std::cout << "store i64 " << toRegister(load(node["start"], level), level) << ", i64* " << ptr << "\n";
    indent(level); std::cout << "br label %c" << id << "\nc" << id << ":\n";
    indent(level+1); std::cout << "%cv" << id << " = load i64, i64* " << ptr << "\n";
    indent(level+1); std::cout << "%il" << id << " = icmp slt i64 %cv" << id << ", " << toRegister(load(node["end"], level+1), level+1) << "\n";
    indent(level+1); std::cout << "br i1 %il" << id << ", label %b" << id << ", label %f" << id << "\nb" << id << ":\n";
    loops.push_back({id, id});
    emitBlock(node["body"], level+1);
    loops.pop_back();
    indent(level+1); std::cout << "%v" << id << " = load i64, i64* " << ptr << "\n";
    indent(level+1); std::cout << "%nx" << id << " = add i64 %v" << id << ", 1\n";
    indent(level+1); std::cout << "store i64 %nx" << id << ", i64* " << ptr << "\n";
    indent(level+1); std::cout << "br label %c" << id << "\nf" << id << ":\n";
    scopes[var].pop_back();
}

void Codegen::emitReturn(const json& node, int level) {
    std::string key = node.contains("argument") ? "argument" : "expr";
    if (node.contains(key) && !node[key].is_null()) {
        std::string res = toRegister(load(node[key], level), level);
        indent(level); std::cout << "call void @fax_fgc_pop_frame()\n";
        indent(level); std::cout << "ret i64 " << res << "\n";
    } else {
        indent(level); std::cout << "call void @fax_fgc_pop_frame()\n";
        indent(level); std::cout << "ret i64 0\n";
    }
}

void Codegen::emitCall(const json& node, int level) {
    std::vector<std::string> args;
    if (node.contains("args")) {
        for (auto& arg : node["args"]) args.push_back(toRegister(load(arg, level), level));
    }
    std::string name = node["name"];
    size_t p = 0;
    while ((p = name.find("::", p)) != std::string::npos) { name.replace(p, 2, "_"); p += 1; }
    indent(level); std::cout << "%ig" << lbl++ << " = call i64 @" << name << "(";
    for (size_t i = 0; i < args.size(); ++i) std::cout << (i > 0 ? ", " : "") << "i64 " << args[i];
    std::cout << ")\n";
}

void Codegen::emitFunction(const json& node) {
    std::string name = node["name"];
    bool isExt = node.value("is_extern", false);

    if (isExt) {
        std::cout << "declare i64 @" << name << "(";
        if (node.contains("args")) {
            for (int i = 0; i < (int)node["args"].size(); ++i) std::cout << (i > 0 ? ", i64" : "i64");
        }
        std::cout << ")\n"; return;
    }

    symbols.clear(); pointers.clear(); types.clear(); scopes.clear();
    std::cout << "\ndefine i64 @" << name << "(";

    std::vector<std::string> argNames;
    if (node.contains("args")) {
        for (int i = 0; i < (int)node["args"].size(); ++i) {
            std::string arg = node["args"][i]["name"];
            std::cout << (i > 0 ? ", " : "") << "i64 %arg_" << arg;
            symbols[arg] = "arg";
            argNames.push_back(arg);

            // Initial type for arguments (can be improved with better type info in JSON)
            std::string at = node["args"][i].value("p_type", "i64");
            std::string mangled = arg + "_arg"; // Special mangling for args to avoid collision
            if (isPointerType(at)) pointers[mangled] = isStringType(at) ? "string" : (at.find("[]") != std::string::npos ? "array" : "struct");
        }
    }
    std::cout << ") {\nentry:\n";
    if (name == "main") { indent(1); std::cout << "call void @fax_fgc_init()\n"; }

    // Temporary scope setup for arguments during collection
    for (auto const& arg : argNames) {
        scopes[arg].push_back(-1); // Use -1 to indicate argument scope
    }

    std::vector<std::string> ptrs;
    if (node.contains("body")) collect(node["body"], ptrs);

    // Reset scopes but keep arguments (mangled correctly)
    scopes.clear();
    for (auto const& arg : argNames) {
        // In Fax, arguments are currently accessed via %arg_name, not a pointer on stack.
        // Wait, I previously changed them to be stored in stack slots for GC.
        // Let's restore that logic but cleanly.
    }

    // Actual pointer collection logic including arguments
    std::vector<std::string> finalPtrs;
    std::map<std::string, std::string> argPtrs;

    if (node.contains("args")) {
        for (auto& argNode : node["args"]) {
            std::string an = argNode["name"];
            std::string at = argNode.value("p_type", "i64");
            int id = lbl++;
            std::string mangled = an + "_" + std::to_string(id);
            nodeIds[&argNode] = id;
            types[mangled] = at;

            std::string ptr = "%" + mangled + "_ptr";
            if (isPointerType(at)) {
                pointers[mangled] = isStringType(at) ? "string" : (at.find("[]") != std::string::npos ? "array" : "struct");
                finalPtrs.push_back(ptr);
            } else {
                indent(1); std::cout << ptr << " = alloca i64\n";
            }
            argPtrs[an] = ptr;
        }
    }

    // Add body pointers
    for (auto const& p : ptrs) finalPtrs.push_back(p);

    indent(1); std::cout << "%_frame = alloca { i8*, i8**, i64 }, align 16\n";
    indent(1); std::cout << "%_rs = alloca [" << std::max((int)finalPtrs.size(), 1) << " x i8**], align 16\n";
    for (int i = 0; i < (int)finalPtrs.size(); ++i) {
        indent(1); std::cout << finalPtrs[i] << " = alloca i8*\n";
        indent(1); std::cout << "store i8* null, i8** " << finalPtrs[i] << "\n";
        indent(1); std::cout << "%_ga" << i << " = getelementptr [" << std::max((int)finalPtrs.size(), 1) << " x i8**], [" << std::max((int)finalPtrs.size(), 1) << " x i8**]* %_rs, i32 0, i32 " << i << "\n";
        indent(1); std::cout << "store i8** " << finalPtrs[i] << ", i8*** %_ga" << i << "\n";
    }

    // Setup GC frame
    indent(1); std::cout << "%_f0 = getelementptr { i8*, i8**, i64 }, { i8*, i8**, i64 }* %_frame, i32 0, i32 1\n";
    indent(1); std::cout << "%_f1 = bitcast [" << std::max((int)finalPtrs.size(), 1) << " x i8**]* %_rs to i8**\n";
    indent(1); std::cout << "store i8** %_f1, i8*** %_f0\n";
    indent(1); std::cout << "%_f2 = getelementptr { i8*, i8**, i64 }, { i8*, i8**, i64 }* %_frame, i32 0, i32 2\n";
    indent(1); std::cout << "store i64 " << (long)finalPtrs.size() << ", i64* %_f2\n";
    indent(1); std::cout << "%_fc = bitcast { i8*, i8**, i64 }* %_frame to i8*\n";
    indent(1); std::cout << "call void @fax_fgc_push_frame(i8* %_fc)\n";

    // Initialize arguments in their slots and scopes
    if (node.contains("args")) {
        for (auto& argNode : node["args"]) {
            std::string an = argNode["name"];
            int id = nodeIds[&argNode];
            scopes[an].push_back(id);
            std::string mangled = an + "_" + std::to_string(id);
            std::string ptr = "%" + mangled + "_ptr";

            if (pointers.count(mangled)) {
                int idCast = lbl++;
                indent(1); std::cout << "%pv" << idCast << " = inttoptr i64 %arg_" << an << " to i8*\n";
                indent(1); std::cout << "store i8* %pv" << idCast << ", i8** " << ptr << "\n";
            } else {
                indent(1); std::cout << "store i64 %arg_" << an << ", i64* " << ptr << "\n";
            }
        }
    }

    if (node.contains("body")) for (auto& stmt : node["body"]) emitStatement(stmt, 1);

    indent(1); std::cout << "call void @fax_fgc_pop_frame()\n";
    indent(1); std::cout << "ret i64 0\n}\n";
}

void Codegen::collect(const json& node, std::vector<std::string>& ptrs) {
    if (node.is_array()) {
        for (auto& item : node) collect(item, ptrs);
        return;
    }
    if (!node.is_object()) return;

    std::string type = node.value("type", "");

    if (type == "Block") {
        std::map<std::string, size_t> checkpoint;
        for (auto const& [name, ids] : scopes) checkpoint[name] = ids.size();
        if (node.contains("body")) collect(node["body"], ptrs);
        for (auto const& [name, size] : checkpoint) {
            while (scopes[name].size() > size) scopes[name].pop_back();
        }
        return;
    }

    if (type == "VariableDeclaration" && node.contains("name")) {
        std::string name = node["name"];
        int id = lbl++;
        nodeIds[&node] = id;

        std::string vt = node.value("var_type", "");
        if (vt == "" && node.contains("expr") && node["expr"].is_object()) {
            const json& expr = node["expr"];
            std::string et = expr.value("type", "");

            if (et == "StringLiteral") vt = "string";
            else if (et == "ArrayLiteral") vt = "array";
            else if (et == "StructLiteral") vt = expr.value("name", "struct");
            else if (et == "Identifier") {
                std::string n = expr.value("value", "");
                if (scopes.count(n) && !scopes[n].empty()) {
                    std::string m = n + "_" + std::to_string(scopes[n].back());
                    if (types.count(m)) vt = types[m];
                }
            } else if (et == "IndexAccess") {
                const json& base = expr["base"];
                if (base.is_object() && base.value("type", "") == "Identifier") {
                    std::string n = base.value("value", "");
                    if (scopes.count(n) && !scopes[n].empty()) {
                        std::string m = n + "_" + std::to_string(scopes[n].back());
                        if (types.count(m)) {
                            std::string bt = types[m];
                            if (bt.length() > 2 && bt.substr(bt.length() - 2) == "[]") vt = bt.substr(0, bt.length() - 2);
                        }
                    }
                }
            } else if (et == "CallExpression") {
                std::string n = expr.value("name", "");
                if (returns.count(n)) vt = returns[n];
            } else if (et == "BinaryExpression" && expr.value("op", "") == "add") {
                auto isStr = [&](const json& op) {
                    if (!op.is_object()) return false;
                    if (isStringType(op.value("type", ""))) return true;
                    if (op.value("type", "") == "Identifier") {
                        std::string n = op.value("value", "");
                        if (scopes.count(n) && !scopes[n].empty()) {
                            std::string m = n + "_" + std::to_string(scopes[n].back());
                            return types.count(m) && isStringType(types[m]);
                        }
                    }
                    return false;
                };
                if (isStr(expr.value("left", json::object())) || isStr(expr.value("right", json::object()))) vt = "string";
            }
        }

        std::string mangled = name + "_" + std::to_string(id);
        scopes[name].push_back(id);
        types[mangled] = vt;

        if (isPointerType(vt)) {
            pointers[mangled] = isStringType(vt) ? "string" : (vt.find("[]") != std::string::npos ? "array" : "struct");
            ptrs.push_back("%" + mangled + "_ptr");
        } else {
            indent(1); std::cout << "%" << mangled << "_ptr = alloca i64\n";
            indent(1); std::cout << "store i64 0, i64* %" << mangled << "_ptr\n";
        }
        return;
    }

    if (type == "IfStatement") {
        if (node.contains("then_branch")) collect(node["then_branch"], ptrs);
        if (node.contains("else_branch")) collect(node["else_branch"], ptrs);
    } else if (type == "WhileStatement" || type == "ForStatement") {
        if (type == "ForStatement") {
            std::string var = node["var_name"];
            int id = lbl++;
            scopes[var].push_back(id);
            std::string mangled = var + "_" + std::to_string(id);
            types[mangled] = "i64";
            // For loops in Fax use a special pointer-less i64 on stack handled in emitFor
        }
        if (node.contains("body")) collect(node["body"], ptrs);
        if (type == "ForStatement") scopes[node["var_name"].get<std::string>()].pop_back();
    } else {
        for (auto it = node.begin(); it != node.end(); ++it) {
            if (it.value().is_object() || it.value().is_array()) collect(it.value(), ptrs);
        }
    }
}

void Codegen::emitPrint(const json& node, int level) {
    Info info = { "0", "i64" };
    if (node.contains("expr")) info = load(node["expr"], level);
    else if (node.contains("args") && !node["args"].empty()) info = load(node["args"][0], level);

    std::string val = toRegister(info, level);
    if (info.type == "bool") {
        int t = lbl++, f = lbl++, e = lbl++;
        indent(level); std::cout << "%it" << lbl++ << " = icmp ne i64 " << val << ", 0\n";
        indent(level); std::cout << "br i1 %it" << (lbl-1) << ", label %L" << t << ", label %L" << f << "\n";
        std::cout << "L" << t << ":\n"; indent(level+1); std::cout << "call i64 (i8*, ...) @printf(i8* getelementptr ([6 x i8], [6 x i8]* @f_t, i32 0, i32 0))\n"; indent(level+1); std::cout << "br label %L" << e << "\n";
        std::cout << "L" << f << ":\n"; indent(level+1); std::cout << "call i64 (i8*, ...) @printf(i8* getelementptr ([7 x i8], [7 x i8]* @f_f, i32 0, i32 0))\n"; indent(level+1); std::cout << "br label %L" << e << "\n";
        std::cout << "L" << e << ":\n";
    } else if (isStringType(info.type)) {
        indent(level); std::cout << "call i64 (i8*, ...) @printf(i8* getelementptr ([4 x i8], [4 x i8]* @f_str, i32 0, i32 0), i8* " << (info.reg[0] == '%' ? info.reg : val) << ")\n";
    } else {
        indent(level); std::cout << "call i64 (i8*, ...) @printf(i8* getelementptr ([5 x i8], [5 x i8]* @f_int, i32 0, i32 0), i64 " << val << ")\n";
    }
}

void Codegen::generate() {
    // Apply optimizations to the AST before code generation
    json optimizedAst = Optimizer::optimize(ast);
    
    emitHeader();
    process(optimizedAst.contains("body") ? optimizedAst["body"] : optimizedAst);
    for (auto const& [val, name] : strings) {
        std::string esc = "";
        for (char c : val) {
            if (c == '\n') esc += "\\0A";
            else if (c == '\"') esc += "\\22";
            else esc += c;
        }
        std::cout << "@" << name << " = private constant [" << (int)val.length()+1 << " x i8] c\"" << esc << "\\00\"\n";
    }
}

}
}